### PR TITLE
refactor: temporally block pages related to pipeline menu

### PR DESCRIPTION
**Pull request by lizable**
## Description
This PR manually blocks pages that are related to pipeline, which needs second phase implementation.
I applied two parts so that user cannot access the pipeline menu by chance.
- [x] Remove pipeline related menu from sidebar 
- [x] Disable and redirect to error page when user input `pipeline` or `pipeline-job` as path variable. 

It will be enabled when we support key features of the MLOps(AIOps).

## Screenshots
- pipeline page
   pipeline-error

- pipeline-job page
   pipeline-job-error

### CODE REVIEW

**Comment by lizable** [comment]
## Updates and Remaining progress

> task with checked means finished and non-checked means that it's ongoing.

- Add `enablePipeline` as a flag whether to enable pipeline feature (requires pipeline-server when login Backend.AI WebUI) or not
   - [ ] Apply AON(All-or-nothing) login when pipeline feature is enabled*
      > Logout when login attempt of either Backend.AI WebUI or of Backend.AI Pipeline fails
   - [ ] Apply Hide/Show when pipeline feature is disabled/enabled
- Found some codes that need refactoring (repetitive conditional statements in reading and assigning values from configuration file(`config.toml`) to global value), So I did two jobs.
   - [x] Wrap conditional(if-else) used for value assigning with utilized function (`_getConfigValueByExists`).
   - [x] Split value assigning from the configuration file(`config.toml`) by section with the number of separate functions
      - general
      - wsproxy
      - resources
      - enviornments

**Comment by lizable** [comment]
> 
## Announcement

Add enablePipeline feature will be handled in a separate issue and PR.

**Review by adrysn — APPROVED** [review]
Tested and login works.

**Review by inureyes — APPROVED** [review]
LGTM

**Review by Sujin-Kim1 — APPROVED** [review]
LGTM

**Pull request merged**
