### PR TITLE
fix: create new resource group

### LINKED ISSUE #975: creation new resource group is failed
**Describe the bug**
GraphQL error when trying to create a new resource group.

**To Reproduce**
1. Go to '/agent' page when you are an admin account.
2. Click on 'RESOURCE GROUP' tap and click on 'add' button
3. Fill the 'ResourceGroupName' field.

**Expected behavior**
create a new resource group.

**Additional context**
this is info of error.
```
title: "400 Bad Request - GraphQL-generated error."
message: "server responded failure: 400 Bad Request - GraphQL-generated error."
type: "https://api.backend.ai/probs/server-error"
```

### PR DESCRIPTION
**Pull request by Sujin-Kim1**
solve the GraphQL error when trying to create a new resource group.

This PR closes #975

### CODE REVIEW

**Review by lizable — CHANGES_REQUESTED** [review]
In my opinion, I would like you to update two things related to user experience in Backend.AI.

First of all, I get an error after I input the resource group name which already exists in creating resource group dialog. I would like you to see how we deal with resource policy name that already exists in these codes below.
- [getting resource policy list](https://github.com/lablup/backend.ai-webui/blob/d68f002bb6a36a389bfb573641dc617edc90c1c9/src/components/backend-ai-credential-view.ts#L401-L403).
- [check custom validity in resource policy input field](https://github.com/lablup/backend.ai-webui/blob/d68f002bb6a36a389bfb573641dc617edc90c1c9/src/components/backend-ai-credential-view.ts#L790-L800)

And also, I would like you to make a consistent UI when showing an invalid input values.
If input field is empty, for now there's no error message below and snackbar message appears right after user clicks create button in the bottom of the dialog.
We can have two choices
- choice 1: to make all error message occurred from invalid input (including empty input) to expose as snackbar
- choice 2: to show error message below the certain input field. (**recommended**)

If you have better ideas, then you can also suggest and apply them.

**Review by lizable — APPROVED** [review]
LGTM

**Comment by inureyes** [comment]
LGTM

**Comment by lizable** [comment]
There are two conflicting files in this branch. Please check the code and resolve the conflicting codes, @Sujin-Kim1 .

**Pull request merged**
