### PR TITLE
fix: modify zIndex of BAIModal to prevent manipulation of the notification drawer

### PR DESCRIPTION
**Pull request by gee05053**
This PR resolves https://github.com/lablup/backend.ai-webui/issues/2183
I set zIndex in BAIModal component and removed zIndex of each modal.

Now Notification drawer can't handle when modal is open

Before
스크린샷 2024-01-29 오전 11 26 24

After
스크린샷 2024-01-29 오후 4 11 37

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by yomybaby** [comment]
@agatha197  Please review this. Thank you.

**Comment by agatha197** [comment]
@gee05053  please resolve the conflicts :)

**Comment by gee05053** [comment]
@agatha197 
I completed to resolve conflicts

**Review by agatha197 — APPROVED** [review]
LGTM

**Pull request merged**
