### PR TITLE
fix: cluster size slider to be active by cluster mode selection

### PR DESCRIPTION
**Pull request by Jaewoook**
## Fixes

- call `updateResourceAllocationPane()` on cluster mode selection handler

### additional comment:

I think `updateResourceAllocationPane()` method need code refactoring. The method cause logical confusion, but I didn't do this because I don't know all intent of condition statement and variables behavior.

---
related issue: #1347

### CODE REVIEW

**Review by Sujin-Kim1 — CHANGES_REQUESTED** [review]
I found this below error.
1. Update resource allocation on the 3rd session page 
2. Set another image on 1st session page
3. Go to the 3rd page
4. Then all custom resource allocations are reset.

**Comment by Jaewoook** [comment]
> I found this below error.
> 
> 1. Update resource allocation on the 3rd session page
> 2. Set another image on 1st session page
> 3. Go to the 3rd page
> 4. Then all custom resource allocations are reset.

I think it's bit more complex to fix. I'll refactor update resource allocation logic after #1360 done.

**Comment by lizable** [comment]
> ## Fixes
> * call `updateResourceAllocationPane()` on cluster mode selection handler
> 
> ### additional comment:
> I think `updateResourceAllocationPane()` method need code refactoring. The method cause logical confusion, but I didn't do this because I don't know all intent of condition statement and variables behavior.
> 
> related issue: #1347

I agree with your opinion, especially in refactoring `updateResourceAllocationPane()`. It does too many things at one function which degrades understanding logic inside. Let's create an issue for that and solve it!

**Review by inureyes — APPROVED** [review]
Let's merge and close this issue. :D

**Pull request merged**
