### PR TITLE
feat: ensure that the logo is always on top at sider.

### PR DESCRIPTION
**Pull request by gee05053**
If layout is too small, sider's contents(logo, menuList, bottomText) is scrolled all.
User must scroll up to click logo to go summary page.
So I added scroll to sider's content to ensure that the logo is always on top.

Before
스크린샷 2024-02-14 오후 3 27 26

After
스크린샷 2024-02-14 오후 5 11 45

**Checklist:** (if applicable)

- [x] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Review by agatha197 — CHANGES_REQUESTED** [review]
Let's add a `fixedTitle` props to the `BAISider` to determine use the fixed title or not.

**Comment by yomybaby** [comment]
Please hold on this PR. The previous UX was intentional. If you want to change UX that is not related to a bug, such as making improvements, please let me know. Thank you.

**Comment by gee05053** [comment]
@yomybaby 
Sorry I didn't know that UX was intentional. I will hold on this PR.

**Comment by yomybaby** [comment]
I close this PR without merging. When we need this feature, we can reopen this PR.

**Pull request closed without merging**
