### PR TITLE
feat: remove legacy user/credential components

### PR DESCRIPTION
**Pull request by ironAiken2**
**Changes:**

This PR removes the functionality for adding new users directly from the credential view. Specifically:

- Removed the `newUserDialog` query and related dialog HTML
- Deleted the `_launchUserAddDialog` and `_addUser` methods
- Removed password validation methods: `_validatePassword`, `_validatePassword1`, `_validatePassword2`
- Deleted the `_togglePasswordVisibility` method

**Rationale:**

The user creation functionality has likely been moved to a separate component or is being handled differently in the application. This change simplifies the credential view by focusing it on credential management rather than user management.

**Impact:**

- Administrators will no longer be able to add new users directly from the credential view
- The user interface for the credential view will be cleaner, without the "Add User" dialog
- Any code relying on the removed methods or dialog will need to be updated

**Checklist:**

- [ ] Update documentation to reflect the removal of user creation from the credential view
- [ ] Ensure that user creation functionality is available elsewhere in the application
- [ ] Test to confirm that credential management features still work as expected
- [ ] Verify that removing these elements doesn't break any existing functionality

### CODE REVIEW

**Comment by ironAiken2** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2755?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2755** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2755?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2754** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2754?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by agatha197 — CHANGES_REQUESTED** [review]
How about moving this PR to the parent of #2757, and removing the credential view file?

**Comment by ironAiken2** [comment]
I've organized the stack so that PR #2754 is merged and used first, but I don't think deleting files is relevant to the actual use of the feature, so I'll stack it above #2757 as you said!

**Review by agatha197 — APPROVED** [review]
LGTM

**Pull request merged**
