### PR TITLE
feat: display kernel node id and idx in Kernel select component

### LINKED ISSUE #2833: Display kernel idx and id in kernel select component

### PR DESCRIPTION
**Pull request by yomybaby**
Resolves #2833

**Changes:**
Enhances the container log modal dropdown by adding node IDs alongside cluster roles. The first 5 characters of each node's row_id are now displayed in a monospace font next to the cluster role, making it easier to identify specific nodes.

**Visual Impact:**
The dropdown now shows entries in the format: `cluster_role (12345)` where the ID portion is styled with a monospace font and secondary color.

### CODE REVIEW

**Comment by yomybaby** [comment]
* **#2832** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2832?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ironAiken2 — APPROVED** [review]
LGTM

**Review by rapsealk — COMMENTED** [review]
LGTM in terms of UI, but I am uncertain if the `kernel.id` provides enough information to users.

**Review by rapsealk — CHANGES_REQUESTED** [review]
Please attach `kernel.cluster_idx` so that users can access via `ssh` to each kernel.

**Comment by yomybaby** [comment]
For admin and superadmin:
image

For others:
image

Also, I changed the sorting function for the Kernel role select's options.

**Review by rapsealk — APPROVED** [review]
LGTM

**Pull request merged**
