### PR TITLE
Attach virtual folder with alias name (#1081)

### PR DESCRIPTION
**Pull request by inureyes**
This PR resolves (#1081)

### CODE REVIEW

**Comment by inureyes** [comment]
image

**Comment by inureyes** [comment]
image

**Review by Taewan-P — CHANGES_REQUESTED** [review]
There are two issues to solve:
  * If the alias name and the folder name are the same, it will not save the alias name and have the previous value.
  * After setting the alias name, deleting the alias name would not delete its value.

**Review by Taewan-P — CHANGES_REQUESTED** [review]
Also, after creating a duplicate alias, deleting with the X mark keeps the folder mapping.

**Comment by Taewan-P** [comment]
This is a suggestion related to UI.
drawing

How about putting the search box above the table? (Above image + some margins)
I also want to hear @Sujin-Kim1 's opinion.

**Review by Taewan-P — APPROVED** [review]
LGTM

**Pull request merged**
