### PR TITLE
fix: side menu icon button ripple to disappear after click

### PR DESCRIPTION
**Pull request by Jaewoook**
## Description
The **Material Web Component**'s **`<icon-button />`** has default ripple component its inside. The problem is the background focus ripple after clicked button is show by default but it does not disappear even user click button's outside after `display: block` -> `display: none`. I think this is mwc's wrong behavior. So I changed background focus not to disappear by default.

## Fixes

- remove remaining ripple from menu drawer's icon button

### Screenshots

**before**
image
> icon button's background focus ripple remained

**after**
image
> icon button's background focus ripple does not appear

---
related issue: #1352

### CODE REVIEW

**Review by Sujin-Kim1 — CHANGES_REQUESTED** [review]
Can you do the same for the menu icon?
image

**Comment by Jaewoook** [comment]
> Can you do the same for the menu icon? image

@Sujin-Kim1  I just changed toggle button to the same style

**Review by lizable — APPROVED** [review]
LGTM. But there's one thing to make clear before merging this PR to main branch. 
@inureyes Should it be better to backport to other versions, such as 21.09 ? IMO, it's a minor cosmetic issue, so we could just apply this to the latest release (22.06 perhaps?)

**Review by Sujin-Kim1 — APPROVED** [review]
LGTM!

**Review by Yaminyam — APPROVED** [review]
LGTM!

**Comment by adrysn** [comment]
I think there is no need to backport this PR.

**Comment by lizable** [comment]
@Yaminyam suggested applying this globally when the icon doesn't actually do any interactions, like opening dialog or something else. And I think It's a good suggestion, and probably we can raise his suggestion as a `good-first-issue`.

**Comment by Jaewoook** [comment]
> @Yaminyam suggested applying this globally when the icon doesn't actually do any interactions, like opening dialog or something else. And I think It's a good suggestion, and probably we can raise his suggestion as a `good-first-issue`.

I agree with this opinion. 👍 However we should take cafe of that there's another library (weightless) icon button component. I think the behavior between two libraries are different.

**Pull request merged**
