### PR TITLE
feat: Improve model card layout and add descriptions to the model store list

### PR DESCRIPTION
**Pull request by agatha197**
follows #2533 

### TL;DR

Dynamically adjust the size and layout of the model card based on the data. If all data is available, display it in two wide columns.

### What changed?

1. Display in two columns if both description and README exist, and in one column if only one exists. Also, dynamically adjust the size of the modal.
2. Partially reverted the content of #2533 to display the description content in card format.
3. Do not display if description does not exist.
4. Add descriptions to the model store list cards and make it searchable.

### How to test?

1. Navigate to the component displaying the `ModelCardModal`.
2. Ensure the modal's width, description's column span, and README column span adjust dynamically as described.
3. Check description is displayed. The maximum row is 3 and not expandable.
4. The description is searchable.

### Why make this change?

To improve user experience by making long model descriptions more manageable and readable without overwhelming the view with too much text initially.

### Screenshots
- all items

- without description

- without README.md

- without description and README.md

- Add description

**Checklist:** (if applicable)

- [x] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [x] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by agatha197** [comment]
* **#2543** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2543?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yomybaby — CHANGES_REQUESTED** [review]
Please check this bottom. Markdown card height. 😀

**Comment by agatha197** [comment]
> 
> 
> Please check this bottom. Markdown card height. 😀

Updated!
image

**Review by ironAiken2 — APPROVED** [review]
LGTM

**Review by lizable — APPROVED** [review]
LGTM.

**Review by yomybaby — APPROVED** [review]
LGTM!

**Pull request merged**
