### PR TITLE
Indentation fix.

### PR DESCRIPTION
**Pull request by baranyeni**
Please care about spaces and indentations 🙏🏻

### CODE REVIEW

**Comment by inureyes** [comment]
@baranyeni  It is automatically generated document, not from human. So if we fix indentations in `docs` directory, it will revert right after we update the document with sphinx...

**Review by inureyes — COMMENTED** [review]
It is not a human-made document. Therefore the modifications will be reverted by automatic document generator.

**Comment by baranyeni** [comment]
I loved the idea of this usage of github of your team! It is really great work and I will try to help as much as possible on those issues. This was like a trial pull-request from me to see whether or not you guys really read those actions or simply discard them. Thanks for your reply and helpful advice on this.

**Comment by inureyes** [comment]
@baranyeni  :+1:

**Pull request closed without merging**
