### PR TITLE
test: e2e test for parsing config.toml and modifying

### PR DESCRIPTION
**Pull request by ironAiken2**
### TL;DR

Updated e2e tests for config.toml and added TOML parsing functionality.

### What changed?

- Removed `config-test.toml` file
- Updated `config.test.ts` to include new tests for blocklist and showNonInstalledImages
- Modified `test-util.ts` to include a new `modifyConfigToml` function
- Added `@iarna/toml` dependency to `package.json` and `pnpm-lock.yaml`

The toml parser currently used by webui has a lot of [issues](https://github.com/lablup/backend.ai-webui/issues/2382), so I used a different library, [`@iarna/toml`](https://github.com/iarna/iarna-toml).

### How to test?

1. Run the e2e tests for the config.toml file:
   - Test the blocklist functionality by checking if specified menu items are hidden and their pages are inaccessible
   - Test the showNonInstalledImages setting by verifying the visibility of non-installed images

2. Verify that the `modifyConfigToml` function works correctly by running the tests and checking if the config.toml file is modified as expected

### Why make this change?

This change improves the e2e testing capabilities for the config.toml file, allowing for more dynamic and comprehensive testing of configuration options. The addition of TOML parsing functionality enables easier manipulation of the config file during tests, providing a more flexible and maintainable testing approach.

---

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#2705** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2705?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by lizable — CHANGES_REQUESTED** [review]
please update package.json file and could we use "https://www.npmjs.com/package/smol-toml" instead of iarna/toml package?
The last update is about 4 years ago, so I think it's better to use the package with active updates.

**Comment by ironAiken2** [comment]
For the toml parser library, I chose the library with the highest weekly downloads because I think it's a library that won't need frequent modifications once the code is established.

**Comment by lizable** [comment]
Okay, Let's apply this library for now.

**Review by lizable — APPROVED** [review]
LGTM.

**Pull request merged**
