### PR TITLE
feat: Disable the time before the current HH:MM:SS for today's date

### PR DESCRIPTION
**Pull request by agatha197**
The `BatchSessionScheduledTimeSetting` component has been updated to enhance date handling and error messaging. The key changes include:

- Added `localFormat` prop to date picker for consistent date formatting.
- Refined conditional rendering for schedule time messages.
- Introduced new error message when the scheduled time is in the past.
- Improved user feedback with contextual messages based on the current state of the `scheduleTime`.
 
### How to Test:
1. Navigate to the component and enable the schedule time setting.
2. Verify that the date picker only allows future dates and uses local date formatting.
3. Check that appropriate messages are displayed based on the selected schedule time:

   - A warning message if no schedule time is set.
   - A secondary message indicating the time remaining if the schedule time is in the future.
   - A danger message if the schedule time is in the past.

### Motivation:
This update aims to provide a clearer and more informative user experience by ensuring accurate date handling and better contextual messages.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [x] Specific setting for review (eg., KB link, endpoint or how to setup)
- [x] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by agatha197** [comment]
* **#2621** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2621?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by gahyuun — APPROVED** [review]
LGTM

**Review by ironAiken2 — CHANGES_REQUESTED** [review]
I'm sure this isn't common, but if you set the availability equal to the current minute, the seconds portion of the datepicker will keep changing. How about setting the minutes of availability to a minute or two behind the current one?

**Review by yomybaby — APPROVED** [review]
LGTM

**Review by ironAiken2 — APPROVED** [review]
LGTM

**Pull request merged**
