### PR TITLE
Add toggle visibility function and button at login page

### PR DESCRIPTION
**Pull request by gee05053**
This PR resolves https://github.com/lablup/backend.ai-webui-ossca-2023/issues/6.
Users can see password they entered.

스크린샷 2023-08-10 오후 2 32 17
Before PR

스크린샷 2023-08-10 오후 2 32 55
After PR

### CODE REVIEW

**Review by yomybaby — CHANGES_REQUESTED** [review]
Thank you. 
Please check these areas agin(red box). It's still FAFAFA.  
image

**Comment by gee05053** [comment]
@yomybaby 
I modified color according your comment!

스크린샷 2023-08-14 오후 1 52 06

**Comment by gee05053** [comment]
I modified padding size and visible toggle button position
Please check one more time!

Before
스크린샷 2023-08-14 오후 4 57 22

After
스크린샷 2023-08-14 오후 4 57 59

Before
스크린샷 2023-08-14 오후 5 24 19

After
스크린샷 2023-08-14 오후 5 20 55

**Review by yomybaby — APPROVED** [review]
LGTM! Thank you

**Pull request merged**
