### PR TITLE
fix: prevents resource policy updates with incorrect values

### LINKED ISSUE #1336: Block invalid value updates in resource policy
**Describe the bug**
If the user inputs an invalid value to resource policy, the bottom border turns red but it can be updated.

**To Reproduce**
1. Go to 'Users' page (for admin)
2. Click on 'Resource Policy' tab
3. Update resource policy by clicking the setting icon button.
4. Input invalid value to RAM or FGPU fields (higher than the maximum value or lower than the minimum value)
5. See error

**Expected behavior**
Automatically change to a values within a given range.

**Screenshots**
image
image

### PR DESCRIPTION
**Pull request by Sujin-Kim1**
- refactor: rename some variables for matching naming convention
- this resolves #1336

### CODE REVIEW

**Review by adrysn — COMMENTED** [review]
I was unable to see an error in the main branch when I updated a resource policy with a large value of cores (eg. 5120). It just automatically decreased to 512, which is the max of the input field. So, can you help me to understand the purpose of this PR?

**Comment by Sujin-Kim1** [comment]
> I was unable to see an error in the main branch when I updated a resource policy with a large value of cores (eg. 5120). It just automatically decreased to 512, which is the max of the input field. So, can you help me to understand the purpose of this PR?

**FYI, instead of blocking create / update when users input a value that does not fit into the existing range, I modified it to automatically change to a value within the range.**

There was a problem with updating when values out of range were entered for RAM and fGPU. This problem is caused by not considering min and max values when the step (based on the value increased or decreased by pressing the arrow button) is decimal. As @adrysn mentioned, I think it's better to automatically convert when users input a value that doesn't fit the range, so I modified the validate function, so please check it again.

**Comment by adrysn** [comment]
Sorry, but I still could not get it. In the **main** branch, I entered large numbers on CPU and GPU resources, but they rounded down to the maximum value of the inputs (see below move). Can you please give me an example in the main branch that causes the issue?

Uploading 화면 기록 2022-07-06 23.45.28.mov…

**Comment by Sujin-Kim1** [comment]
> Sorry, but I still could not get it. In the **main** branch, I entered large numbers on CPU and GPU resources, but they rounded down to the maximum value of the inputs (see below move). Can you please give me an example in the main branch that causes the issue?
> 
>  2022-07-06.23.45.28.mov

I meant the **RAM and fGPU** cause an error like below. (I tested it in the main branch)

https://user-images.githubusercontent.com/28584164/177692622-83a46adf-a145-48da-810e-18e403b6ca74.mov

Don't we need to fix it?

**Comment by adrysn** [comment]
> > Sorry, but I still could not get it. In the **main** branch, I entered large numbers on CPU and GPU resources, but they rounded down to the maximum value of the inputs (see below move). Can you please give me an example in the main branch that causes the issue?
> > 2022-07-06.23.45.28.mov
> 
> I meant the **RAM and fGPU** cause an error like below. (I tested it in the main branch)
> 
>  2022-07-07.1.38.45.mov 
> 
> Don't we need to fix it?

Okay. For the memory and fGPUs.

**Review by adrysn — CHANGES_REQUESTED** [review]
LGTM. But, I think the max value of memory, 1024 GB, is too small. The newest DGX systems have 2 TB of memory nowadays. Let's increase the max to a greater value, such as 100 TB.

**Comment by Sujin-Kim1** [comment]
> LGTM. But, I think the max value of memory, 1024 GB, is too small. The newest DGX systems have 2 TB of memory nowadays. Let's increase the max to a greater value, such as 100 TB.

Thanks for reviewing! I updated the max value to 100TB. But it might be updated after merging https://github.com/lablup/backend.ai-webui/pull/1328

**Review by adrysn — APPROVED** [review]

**Pull request merged**
