### PR TITLE
feature: Change ServiceLauncherModal to page

### PR DESCRIPTION
**Pull request by agatha197**
This pull request overhauls the Service Launcher functionality, introducing navigation paths and refactoring components to improve maintainability and code clarity. Key changes include:

1. **Lazy Loading and Routing:**
   - Added new routes for '/service/start' and '/service/update/:endpointId'.
   - Incorporated these routes into the browser router with `React.lazy` for components to enhance performance with lazy loading.

2. **Component Renaming and Refactoring:**
   - Renamed `ServiceLauncherModal` to `ServiceLauncherPageContent` and updated all relevant imports and exports.
   - Split `ServiceLauncherModal` into multiple components for better readability and separation of concerns.

3. **Code Cleanup:**
   - Removed unused states and props from components.
   - Utilized `useWebUINavigate` for navigation instead of state-based modals.

4. **Updates to Endpoint Pages:**
   - Modified the service update workflow to navigate to the new ServiceLauncherPage.

5. **Internationalization:**
   - Added translations for new terms such as 'Start New Service' and 'Update Service' in multiple languages.

### How to test
endpoint: 10.100.64.15

---

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [x] Specific setting for review (eg., KB link, endpoint or how to setup)
- [x] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by agatha197** [comment]
* **#2508** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2508?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by lizable — COMMENTED** [review]
LGTM. I guess we can split the page into 3 for understanding.

**Review by lizable — APPROVED** [review]

**Comment by agatha197** [comment]
> LGTM. I guess we can split the page into 3 for understanding.

Yes, it is possible. However, @yomybaby and I have decided to split in the next step.

**Review by yomybaby — APPROVED** [review]
LGTM

**Pull request merged**
