### PR TITLE
refactor: improve error handling of `CustomizedImageList`

### PR DESCRIPTION
**Pull request by agatha197**
**Changes:**
Improves error handling when deleting customized images by:
- Adding specific error checks for `forget_image_by_id` and `untag_image_from_registry` operations
- Displaying individual error messages from the error array with 2.5s duration
- Only showing success message and refreshing the environment when all operations complete successfully

**Checklist:**
- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

**Test Cases:**
1. Delete an image with `forget_image_by_id` failure
2. Delete an image with `untag_image_from_registry` failure
3. Delete an image with multiple GraphQL errors
4. Delete an image successfully

### CODE REVIEW

**Comment by agatha197** [comment]
* **#2792** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2792?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ironAiken2 — COMMENTED** [review]
Is there a way to cause a failure for `forget_image_by_id` or `untag_image_from_registry`?

**Comment by agatha197** [comment]
it was possible before https://github.com/lablup/backend.ai/pull/3004 is merged 😅

**Review by yomybaby — APPROVED** [review]
LGTM

**Pull request merged**
