### PR TITLE
feat: BAIProperty filter supports `boolean` type

### PR DESCRIPTION
**Pull request by yomybaby**
### TL;DR

Added support for boolean options in BAIPropertyFilter component.

Related core PR: https://github.com/lablup/backend.ai/pull/2605

### What changed?

1. `AgentList.tsx`: Added `type` and `options` properties to filter properties.
2. `BAIPropertyFilter.stories.tsx`: Updated story to include boolean type property.
3. `BAIPropertyFilter.tsx`: Major updates to support boolean options including default boolean filter options and enhanced value handling.
4. Updated i18n files for new labels.

### How to test?

1. Go to the AgentList component and verify the filter functionality with boolean options.
2. Check the storybook for BAIPropertyFilter and ensure the new boolean property works as expected.
3. Verify i18n changes reflect correctly in the UI.

### Why make this change?

To enhance the filtering capabilities by allowing boolean options, providing more flexibility and utility in data filtering.

---

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by yomybaby** [comment]
* **#2603** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2603?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by agatha197** [comment]
It doesn't work :( And please resolve lint errors.
image
image

**Review by agatha197 — CHANGES_REQUESTED** [review]
It doesn't work :( And please resolve lint errors.
image
image

**Comment by yomybaby** [comment]
Sorry @agatha197 , I forgot to mention related core PR https://github.com/lablup/backend.ai/pull/2605 .
It's already merged. Please test again.

**Review by agatha197 — APPROVED** [review]
LGTM!

**Pull request merged**
