### PR TITLE
add: confirmation dialog on force-terminate attempt on PULLING/PREPARING/TERMINATING

### PR DESCRIPTION
**Pull request by lizable**
* Related: [backend.ai#2275](https://github.com/lablup/backend.ai/pull/2275)
This PR adds confirmation dialog when the user wants to "force-terminate" session(s).

### Screenshot(s):
* Superadmin trying to terminate session(s) which contains actual containers:
Screenshot 2024-07-03 at 8 06 44 PM

* User trying to terminate session(s) regardless of the session actually have containers or Superadmin trying to terminate session(s) which does not contain any containers:
Screenshot 2024-07-03 at 8 06 59 PM

### How to test
1. Go to sessions page.
2. Click Terminate icon or check any session records in the session list.
3. Terminate session dialog pops up.
4. Click `FORCE TERMINATE` button.
5. Force terminate confirmation dialog pops upl.
6. Click `FORCE TERMINATE` button in the dialog.
7. See the result. (session(s) in `PREPARING`/`PULLING`/`TERMINATING` will be updated to `TERMINATED` accordingly.)
   - When you logged in with user account or just admin account, the force-terminate operation will fail.
   - However, When you logged in with superadmin account, it will be successfully done.

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minimum required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [x] Minimum requirements to check during review
- [x] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by lizable** [comment]
* **#2481** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2481?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @lizable and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by agatha197 — APPROVED** [review]
LGTM

**Comment by YEONFEEL96** [comment]
Is the following link the correct modification for this PR's screenshot?
Based on our discussion on teams, I guess so. @lizable 
https://github.com/lablup/giftbox/issues/682#issuecomment-2168303822

**Review by agatha197 — APPROVED** [review]
LGTM

**Review by YEONFEEL96 — APPROVED** [review]
LGTM!

**Pull request merged**
