### PR TITLE
feat: support port range type in `PortSelectFormItem`

### PR DESCRIPTION
**Pull request by yomybaby**
### TL;DR

Resolve https://github.com/lablup/giftbox/issues/692

The validation for port selection has been enhanced to include port ranges, ensuring accurate representation and error handling for user inputs.

### What changed?
- Updated the validation logic in `PortSelectFormItem` to accept port ranges.
- Enhanced `PortTag` component to validate and correctly display port ranges.
- Added helper functions `parsePortRangeToStringArray` and `isValidPortRange` to assist in parsing and validating port ranges.

### How to test?
1. Navigate to the port selection form item.
2. Enter individual ports and port ranges.
3. Ensure the ports and port ranges are correctly validated and displayed.
4. Check for any error messages for out-of-range or invalid port entries.
5. Create a session with port range setting.

### Why make this change?
This change improves user experience by allowing a more flexible input method for selecting multiple consecutive ports and ensures correct validation and display of port information.

### CODE REVIEW

**Comment by yomybaby** [comment]
* **#2506** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2506?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @yomybaby and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by agatha197 — CHANGES_REQUESTED** [review]
Should we perform validation in advance to prevent users from setting the same port? In the past, only a single port was allowed, so there was no chance of overlap. However, now that we have added a range type, there may be overlapping ports.

**Review by agatha197 — CHANGES_REQUESTED** [review]
The translation did not update.

**Review by agatha197 — APPROVED** [review]
LGTM

**Pull request merged**
