### PR TITLE
feat: cloning vfolder

### LINKED ISSUE #899: Provide cloning Vfolder feature
**Is your feature request related to a problem? Please describe.**
기능 요청이 특정 문제에 연관된 것이라면 여기에 그 문제를 설명해주세요.
Currently, the only way to copy all of the contents in the Vfolder to another one is to mount them in the session and copy them through the Web terminal. Unfortunately, that operation does not support cloning the Vfolder as itself, It only supports cloning to subdirectories of another Vfolder.

**Describe the solution you'd like**
어떤 기능이 있으면 좋겠는지 자세히 설명해주세요.
Supporting Vfolder cloning feature by simple UI such as a button clicking.
Also, if Vfolder name already exists, the folder name should be automatically changed by adding ``_``(underscore) with numbers.

**Describe alternatives you've considered**
혹시 다른 대안들을 생각해본 적이 있다면 함께 적어주세요.

**Additional context**
기능 요청에 대해 보다 잘 이해할 수 있는 다른 맥락을 기술해주세요.
To see API Function, check out the manager code below.
[Backend.AI Manager Code for Vfolder cloning
](https://github.com/lablup/backend.ai-manager/blob/edf3280ae0168e77772c3ee2d79c9483ee008e95/src/ai/backend/gateway/vfolder.py#L1327-L1455)

### PR DESCRIPTION
**Pull request by lizable**
> NOTICE: This feature is only available in version 20.09 or higher, after [the feature branch of manager repository](https://github.com/lablup/backend.ai-manager/pull/393) is merged.

This PR resolves #899.

### CODE REVIEW

**Comment by lizable** [comment]
Since the related feature in the [manager branch has been merged](https://github.com/lablup/backend.ai-manager/pull/393), It seems OK to merge this PR. could you review this PR @inureyes  @adrysn ?

**Comment by inureyes** [comment]
@lizable We need a manager backport plan to 20.09 since the version conditional routine uses 'storage-proxy'.

**Comment by inureyes** [comment]
> @lizable We need a manager backport plan to 20.09 since the version conditional routine uses 'storage-proxy'.

I checked and confirmed that It is backported to 20.09.

**Review by inureyes — APPROVED** [review]
LGTM

**Pull request merged**
