### PR TITLE
feat: new chatting page

### PR DESCRIPTION
**Pull request by agatha197**
1. Refactored `EndpointListPage` to `ServingPage` and updated related import statements.
2. Implemented a new `ChattingPage` component for chat functionalities and added endpoint selection.
3. Updated `LLMChatCard` to include a model selection dropdown.
4. Introduced `EndpointLLMChatCard` for integrating endpoint and model selection in chat.
5. Added translations for new strings in multiple languages.
6. Removed unused import statements and fixed minor styling issues.

### How to test
1. Go to `/serving?tab=chatting`
2. Select the endpoint and model of each chatting card.
3. If you want to add the chatting card, click the add icon in the top corner.
4. Click the delete button to delete each chatting card.

### Screenshots

---

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by agatha197** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2560?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2560** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2560?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2554** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2554?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2553** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2553?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ironAiken2** [comment]
If the model endpoint is changed (added, modified, deleted, etc.) it seems to be reflected late in chatting UI (not reflected in the endpoint settings dropdown)

Also, after creating multiple chatcards, when I go to another page, it resets to the default of 2. I wonder if this is the intended logic.

**Review by ironAiken2 — CHANGES_REQUESTED** [review]
If the model endpoint is changed (added, modified, deleted, etc.) it seems to be reflected late in chatting UI (not reflected in the endpoint settings dropdown)

Also, after creating multiple chatcards, when I go to another page, it resets to the default of 2. I wonder if this is the intended logic.

**Comment by agatha197** [comment]
It's true that the chat list disappears after moving to another page or refreshing it, because it doesn't have the ability to save conversation records yet haha :'(

**Review by yomybaby — APPROVED** [review]
LGTM

**Review by ironAiken2 — APPROVED** [review]
LGTM

**Pull request merged**
