### PR TITLE
fix: improve `message`'s i18n and duration for model services deletion 

### PR DESCRIPTION
**Pull request by ironAiken2**
### What I Fixed
Changed the wording that appears when a model service is terminated. Currently, when you request a service to be terminated, it doesn't happen immediately, but takes a while because it depends on some dependencies, so I've changed the wording to be more request-driven.
### Feature
|before|after|
|---|---|
|||

**Checklist:** (if applicable)

- [ ] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by ironAiken2** [comment]
* **#2439** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2439?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @ironAiken2 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yomybaby — CHANGES_REQUESTED** [review]
Please check and fix related messages below:

image

**Comment by ironAiken2** [comment]
I made some UI changes for that.
> Please check and fix related messages below:
> 
> image
> 
> 
> 
> 
> 
> 
> 
> 
>

**Review by yomybaby — APPROVED** [review]
LGTM now, please update the AFTER screenshot in description.

**Pull request merged**
