### PR TITLE
feat: add preopen ports configs on the session launcher

### PR DESCRIPTION
**Pull request by Sujin-Kim1**
resolves https://github.com/lablup/backend.ai-webui/issues/1753

## What's changed
- Add `maxCountForPreOpenedPort` which means the maximum allowed number of pre-opened ports.
- Pre-open Ports setting on the session launcher (see details in the screenshots)
- Add some properties to the `lablup-expansion` to set the icon button to both ends.

💡 Updated
- Hide preopen ports configs when `maxCountForPreOpenedPort` is 0.

## Screenshots
- Environment Variable configuration and Pre-open Ports configuration are inside of the `lablup-expansion`.
image
image
image

- Config Modal
image
image

  - If the added row number is same with `maxCountForPreOpenedPort`, the add button will be disabled.
image

- Last page of session launcher
image
image

- Launch session with `preopen_ports` (session app dialog) - will be handled by https://github.com/lablup/backend.ai-webui/issues/1755
image

### CODE REVIEW

**Review by lizable — CHANGES_REQUESTED** [review]
@Sujin-Kim Is there any chance of user(probably not, I guess) could input `0` on `maxCountForPreOpenedPort` that you added as checking whether the number of allowed pre-opened port? If so, well I can still input pre-opened port and of course, execute the session with the port. Please check this video clip below:

https://github.com/lablup/backend.ai-webui/assets/46954439/e018332d-c4ce-4a8f-9283-73c0f568594d

How to reproduce this:
1. Set `maxCountForPreOpenedPort` value in configuration as `0`.
2. Refresh the page (Optional)
3. Click `Start` button in the sessions menu.
4. Session launcher dialog pops up.
5. Click Gear icon in the right side of pre-opened port section
6. Input any value between `1024` to `65535`
7. Click Save button.
8. Click button below the session launcher dialog.
9. App dialog pops up.
10. See the pre-opened port App icon appears (Bug!)

**Comment by Sujin-Kim1** [comment]
> @sujin-kim Is there any chance of user(probably not, I guess) could input `0` on `maxCountForPreOpenedPort` that you added as checking whether the number of allowed pre-opened port? If so, well I can still input pre-opened port and of course, execute the session with the port. Please check this video clip below:
> 
>  Screen.Recording.2023-08-09.at.6.33.25.PM.mov 
> How to reproduce this:
> 
> 1. Set `maxCountForPreOpenedPort` value in configuration as `0`.
> 2. Refresh the page (Optional)
> 3. Click `Start` button in the sessions menu.
> 4. Session launcher dialog pops up.
> 5. Click Gear icon in the right side of pre-opened port section
> 6. Input any value between `1024` to `65535`
> 7. Click Save button.
> 8. Click button below the session launcher dialog.
> 9. App dialog pops up.
> 10. See the pre-opened port App icon appears (Bug!)

Thanks for the detailed review👍🏻 I'll make the additional message to the setting modal if the `maxCountForPreOpenedPort` is 0.

**Comment by Sujin-Kim1** [comment]
Left tasks: close the pre open port config modal when `maxCountForPreOpenedPort` is 0. / Make add button disabled and enabled properly even if reopening the config modal.

**Review by lizable — APPROVED** [review]
LGTM.

**Pull request merged**
