### PR TITLE
fix: round mem and shmem allocation size in panel

### PR DESCRIPTION
**Pull request by ggstone0523**
### Resolve: lablup/backend.ai-webui #1122

- This bug is caused by overflow the property(cpu_request, mem_request, shmem_request, gpu_request) value in "total allocation" panel when allocate large amount of resource.
- Add scroll to "total allocation" panel to prevent overflow.

**test image**
PR4

PR4(2)

### CODE REVIEW

**Review by lizable — CHANGES_REQUESTED** [review]
I'm afraid that we should solve this problem in another way instead of using a horizontal scrollbar. It would degrade user experience, I guess.
How about using a flexible layout? When width is long enough, it shows all in one row, but when content seems to be too much to carry in one row, it splits into two rows.

**Comment by ggstone0523** [comment]
### The revision was completed by reflecting the comments.

- remove scroll in "total allocation" panel
- apply flexible layout to total allocation panel

**test image**
PR4_review1_2

PR4_review1_1

**Comment by ggstone0523** [comment]
### The revision was completed.

- Remove flexible layout from "total allocation" panel
- Round mem allocation size to the first decimal place.
- Round shmem allocation size to the second decimal place.
- "_roundResourceAllocation" function is round the value according to the specified number of digits. 

**test image**
PR4_review2_1

**Review by lizable — APPROVED** [review]
LGTM

**Review by adrysn — CHANGES_REQUESTED** [review]
The code looks okay. Just please resolve the conflict before merge.

**Comment by ggstone0523** [comment]
**The revision was completed by reflecting the comments.**

- resolve the conflict

**Review by adrysn — APPROVED** [review]
LGTM.

**Pull request merged**
