### PR TITLE
fix: 400 error occurs when refreshing container logs

### PR DESCRIPTION
**Pull request by agatha197**
follows #2524 

### TL;DR

This pull request updates the `BackendAISessionList` component to support retrieving logs specific to a selected kernel.

### What changed?

The `get_logs` method of `backendaiclient` has been modified to accept an additional parameter, `kernelId`. If a kernel is selected, logs for that specific kernel will be retrieved. If no kernel is selected, all logs will be retrieved as before. This change affects two places in the `backend-ai-session-list.ts` file where `get_logs` is called.

### How to test?

1. In the UI, select a specific kernel.
2. Trigger a log retrieval action.
3. Verify that the logs retrieved are specific to the selected kernel.
4. Unselect the kernel and trigger log retrieval again.
5. Verify that all logs are retrieved when no kernel is selected.

### Why make this change?

The motivation behind this change is to provide users with the ability to filter logs by specific kernels, which can be useful for debugging and monitoring purposes.

---

**Checklist:** (if applicable)

- [x] Mention to the original issue
- [ ] Documentation
- [ ] Minium required manager version
- [ ] Specific setting for review (eg., KB link, endpoint or how to setup)
- [ ] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by agatha197** [comment]
* **#2536** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2536?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by yomybaby — CHANGES_REQUESTED** [review]
Please below error:
```
{
    "type": "https://api.backend.ai/probs/object-not-found",
    "title": "No such kernel.",
    "msg": "Session has no such kernel (sid:915e6e35-57c7-46e9-9750-81a5e7de3e62, kid:5d2d50f6-bdb6-40cd-b4b9-eefbd6b2285f))"
}
```
You can reproduce this erorr
- create a session
- click a container log button right after creating

**Comment by lizable** [comment]
## Updates
This PR also fixes fetching and showing container log when changing the current session.
Also, It hides kernel id select UI when server doesn't support per kernel log fetching feature which will be applied in `24.03.7` (resolved in [backend.ai#2364](https://github.com/lablup/backend.ai/pull/2364))

**Review by lizable — APPROVED** [review]
LGTM.

**Review by yomybaby — APPROVED** [review]
LGTM

**Pull request merged**
