### PR TITLE
feat: Individual `error_msg` for cards to prevent total list fetch disruption

### PR DESCRIPTION
**Pull request by agatha197**
related PR: https://github.com/lablup/backend.ai/pull/2570

This pull request includes the following changes:

1. **Error message handling:**
   - Added error message (`error_msg`) field to `ModelCard`, and `ModelStoreListPage` components. This error messages are displayed only to superadmin and owners.
   - Updated `ModelCardModal`, `ModelStoreListPage`, and other related components to properly display error messages when they are present.
   - Added `Alert` and `Empty` components to provide better user feedback in case of errors. 
2. **Architecture default value update:**
   - Changed the default value for the `architecture` field in various GraphQL types (`Queries`, `Mutations`) from "aarch64" to "x86_64".

### How to test?
1. core part: checkout https://github.com/lablup/backend.ai/pull/2570
2. add a model store type (project type, model usage mode, model-store project needed)
3. add a `model-definition.yml` file referring gitbook. (if you don't know the gitbook address, please ask @agatha197)
4. the way to add a file to the model store type folder is not supported yet. so you should use scp, ssh, or others. For me, I modified the https://github.com/lablup/backend.ai-webui/blob/main/src/components/backend-ai-data-view.ts#L320 line (model -> model-store) for testing. (FOR JUST TESTING)
5. If you add an empty model-definition.yml or invalid file, you can see the error and you can still see the valid model cards.
6. you can check the details by clicking each model card. If the model card is invalid, the error message and `Empty` component will appear. 

### Why make this change?
These changes enhance the user experience by providing clear and informative error messages per model card and preventing total list fetch disruption. (Before this PR, if there are invalid `model-definition.yml` files in the model store type folder, it isn't possible to fetch all lists of model cards.)

### Screenshots

**Checklist:** (if applicable)

- [x] Mention to the original issue: [Teams Threads](https://teams.microsoft.com/l/message/19:d881f3fe6c1e40fa89b660e1ed32431b@thread.tacv2/1721893074477?tenantId=13c6a44d-9b52-4b9e-aa34-0513ee7131f2&groupId=b1f3bcf4-facf-40d3-94ab-169abb4f0f52&parentMessageId=1720414523279&teamName=customers%20%26%20clients&channelName=KISTI&createdTime=1721893074477)
- [ ] Documentation
- [x] Minium required manager version: 24.03.7
- [x] Specific setting for review (eg., KB link, endpoint or how to setup)
- [x] Minimum requirements to check during review
- [ ] Test case(s) to demonstrate the difference of before/after

### CODE REVIEW

**Comment by agatha197** [comment]
* **#2583** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2583?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rapsealk** [comment]
Please check for the title! (feat: Individual `error_msg` for cards to prevent total list fetch disruption)

**Review by ironAiken2 — CHANGES_REQUESTED** [review]
I confirmed that it's working well. 
However, it is currently showing data for invalid yaml files, which breaks the UI when the amount of data is large.

image

**Review by ironAiken2 — APPROVED** [review]
LGTM

**Pull request merged**
