### PR TITLE
fix: change from `24.09.1.` to `24.09.1`

### PR DESCRIPTION
**Pull request by agatha197**
**Changes:**
Removes trailing periods from GraphQL version annotations across image-related queries. This affects:
- `@since(version: "24.09.1.")` → `@since(version: "24.09.1")`
- `@deprecatedSince(version: "24.09.1.")` → `@deprecatedSince(version: "24.09.1")`

**Rationale:**
Standardizes version string format in GraphQL directives by removing unnecessary trailing periods, making version annotations more consistent.

**Checklist:**
- [ ] Minimum required manager version: 24.09.1
- [ ] Test cases: Verify GraphQL queries continue to work with updated version annotations

### CODE REVIEW

**Comment by agatha197** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2807?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#2807** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2807?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#2800** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2800?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2805** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2805?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2795** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2795?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2794** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2794?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2796** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2796?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2789** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2789?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#2788](https://github.com/lablup/backend.ai-webui/pull/2788) <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2788?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#2787** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2787?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#2785** <a href="https://app.graphite.dev/github/pr/lablup/backend.ai-webui/2785?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @agatha197 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ironAiken2 — APPROVED** [review]
LGTM

**Review by yomybaby — APPROVED** [review]
LGTM

**Comment by yomybaby** [comment]
This change is absorbed parents stack. I close this without merging.

**Pull request closed without merging**
