### PR TITLE
fix: make available to select project in creating the project data folder

### LINKED ISSUE #1492: Unable to change the project in creating a project data folder
### What Operating System(s) are you seeing this problem on?

Linux (aarch64)

### Backend.AI version

22.9.2

### Describe the bug

I was trying to create a project folder as an admin. However, I found that I cannot select the items under "Project" dropdown list.
image

### To Reproduce

* Log in as an admin.
* Try to create a project folder by changing the "Project" dropdown.

### Expected Behavior

Should be able to change the project.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Sujin-Kim1**
resolves #1492

### CODE REVIEW

**Review by yomybaby — APPROVED** [review]
LGTM!

**Comment by yomybaby** [comment]
I just want to mention one thing not related to this issue so much.  

On this file, `this.allowed_folder_type` has always `as string[]`. 
Let's remove `as string[]` and change below line 


https://github.com/lablup/backend.ai-webui/blob/42a8559d630041ce818afaee8a500532172e78a3/src/components/backend-ai-data-view.ts#L77

```typescript
@property({type: Array}) allowed_folder_type:string[] = [];
```

**Comment by Sujin-Kim1** [comment]
> Member

reflected!

**Comment by yomybaby** [comment]
It works properly now.

**Pull request merged**
